
import os
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings, ChatOpenAI


# ==========================
# Retrieval component
# ==========================

def retrieve_relevant_chunks(query, vectorstore, k=3):
    """
    Retrieve relevant chunks from the vectorstore based on the query.

    Args:
        query (str): The input query.
        vectorstore (Chroma): The Chroma vectorstore instance.
        k (int): Number of relevant chunks to retrieve.
        
    Returns:
        list: A list of relevant chunks.
    """
    print(f"\nRetrieving relevant chunks for query: '{query}'")
    results = vectorstore.similarity_search_with_score(query, k=k)

    retrieved_chunks = []
    for doc, score in results:
        retrieved_chunks.append({
            "content": doc.page_content,
            "score": score,
            "metadata": doc.metadata
        })

    print(f"\nRetrieved {len(retrieved_chunks)} relevant chunk(s)")
    return retrieved_chunks

# ==========================
# Prompting component
# ==========================

def generate_prompt(retrieved_chunks, query):
    """
    Generate a prompt for the LLM based on retrieved chunks and the user query.

    Args:
        retrieved_chunks (list): List of relevant chunks.
        query (str): The input query.
    returns:
        str: The generated prompt for the LLM.
    """
    print("\nGenerating prompt for the LLM...")
    context = "\n\n".join([chunk['content'] for chunk in retrieved_chunks])

    prompt = f"""
    You are a helpful assistant. Please answer the following question based on the provided context:

    Instructions:
    - Use only the information provided in the context to answer the question.
    - If the answer is not present in the context, respond with "I don't know."
    - Do not make up information or provide answers based on external knowledge.
    - Ensure that your response is clear, concise, and directly addresses the question.
    - Cite any relevant information from the context in your answer.
    
    Question: {query}

    Context:
    {context}
    
    Answer: 
    """
    print("Prompt generated successfully.")
    
    return prompt

# ==========================
# Generation component
# ==========================

def generate_answer(prompt, model="gpt-3.5-turbo", temperature=0.3):
    """
    Generate an answer using the LLM based on the provided prompt.

    Args:
        prompt (str): The prompt for the LLM.
        model (str): The model to use for generation.
        temperature (float): The temperature for generation.
    Returns:
        str: The generated answer from the LLM.
    """
    print("\nGenerating answer using the LLM...")
    
    llm = ChatOpenAI(
        model=model,  # You can choose a different model if needed
        api_key=os.getenv("OPENAI_API_KEY"),  # Use the API key from environment variables
        temperature=temperature
    )

    response = llm.invoke(prompt)
    
    print("Response generated successfully.")
    return response.content.strip()



# ==========================
# Complete RAG query pipeline
# ==========================

def run_rag_pipeline(question, vectorstore, k=3, verbose=True):
    """
    Run the complete RAG pipeline: retrieval, prompting, and generation.

    Args:
        question (str): The input question.
        vectorstore (Chroma): The Chroma vectorstore instance.
        k (int): Number of relevant chunks to retrieve.
        verbose (bool): Whether to print detailed logs.
        
    Returns:
        str: The final answer generated by the LLM.
    """
    print("\n" + "="*70)
    print("RAG QUERY PIPELINE")
    print("="*70)
    
    if verbose:
        print(f"\nRunning RAG pipeline for question: '{question}'")

    # Step 1: Retrieve relevant chunks
    retrieved_chunks = retrieve_relevant_chunks(question, vectorstore, k=k)

    if verbose:
        print(f"\nRetrieved {len(retrieved_chunks)} relevant chunk(s):")
        for i, chunk in enumerate(retrieved_chunks, start=1):
            print(f"{i}. Score: {chunk['score']:.4f}")
            print(f"Content: {chunk['content'][:200]}...")
    
    # Step 2: Generate prompt for the LLM
    prompt = generate_prompt(retrieved_chunks, question)

    if verbose:
        print(f"\nGenerated Prompt Length: {len(prompt)} characters")
    
    # Step 3: Generate answer using the LLM
    answer = generate_answer(prompt)

    if verbose:
        print(f"\nFinal Answer:\n{answer}")

    return {
        "question": question,
        "answer": answer,
        "retrieved_chunks": retrieved_chunks,
        "number_of_chunks": len(retrieved_chunks)
    }
    
    
# ==========================
# Main execution block
# ==========================

if __name__ == "__main__":
    from dotenv import load_dotenv
    from pathlib import Path
    
    
    load_dotenv()  # Load environment variables from .env file
    api_key = os.getenv("OPENAI_API_KEY")  # Get the OpenAI API key from environment variables

    BASE_DIR = Path(__file__).resolve().parent
    DOCUMENTS_DIR = BASE_DIR / "documents"
    file_path = DOCUMENTS_DIR / "Destiny_Lore_Summary.pdf"  # Replace with your document path

    print("\nLoading vector store from persisted directory...")
    embeddings = OpenAIEmbeddings(
        model="text-embedding-3-small",  # You can choose a different model if needed
        api_key=api_key  # Use the API key from environment variables
    )
    
    vectorstore = Chroma(
        persist_directory="./chroma_db",  # Directory where the vector store is persisted
        embedding_function=embeddings
    )
    print(f"Vector store loaded successfully from './chroma_db'.")
    
    
    question = str(input("\nEnter your question: "))
    
    result = run_rag_pipeline(question, vectorstore, k=3, verbose=True)
    print("\n" + "="*70)
    print("RAG PIPELINE RESULT")
    print("="*70)
    
    print(f"\nQuestion: {result['question']}")
    print(f"\nAnswer: {result['answer']}")
    print(f"\nNumber of Retrieved Chunks: {result['number_of_chunks']}")
    print("="*70)